"""
================================================================================
脚本名称: run_paper_figures.py
功能概述: 论文图表数据准备与流程编排
================================================================================

【职责说明】
    本脚本只负责：
      1. 解析命令行参数
      2. 加载各类结果数据（AnnData、niche CSV 等）
      3. 按 Figure 1 → 5 顺序调用 paper_plot_functions.py 中的绘图函数

    ★ 若需修改绘图样式、颜色、字号、图幅大小，请编辑：
      code/pipeline/paper_plot_functions.py

【上游依赖】
    results/HCC4R/spatial_niche/spatial_niche_scores.csv         (Step 2)
    results/HCC4R/spatial_niche/immunosuppressive_niche_signature_genes_ranked.csv
    results/HCC4R/adata_vis_post.h5ad                            (Step 1)
    results/HCC4R/adata_sc_post.h5ad                             (Step 1)
    results/CHC20/adata_vis_post.h5ad                            (可选，Figure 5)
    results/HCC4R/spatial_niche/immunosuppressive_niche_signature_genes.txt
    results/CHC20/adata_vis_post.h5ad                            (Figure 5A/5B signature projection)

【使用方式】
    # 先运行 Step 1 + Step 2（以 HCC4R 为主）：
    python code/run_hcc4r.py

    # 再生成论文图表：
    python code/pipeline/run_paper_figures.py

    # 或通过入口脚本一键运行：
    python code/run_hcc4r.py --paper-figures
    python code/run_hcc4r.py --figures-only
================================================================================
"""
from __future__ import annotations

import argparse
import logging
import shutil
import sys
import warnings
from pathlib import Path
from typing import Optional

import anndata as ad
import pandas as pd

warnings.filterwarnings("ignore")

# 导入所有绘图函数（修改样式请去 paper_plot_functions.py）
from paper_plot_functions import (  # noqa: E402
    PAPER_DPI,
    plot_fig1A_workflow,
    plot_fig2A_HE,
    plot_fig2B_spatial_abundance,
    plot_fig2C_coloc_heatmap,
    plot_fig3A_spatial_domain,
    plot_fig3B_domain_composition,
    plot_fig3C_score_violins,
    plot_fig4A_volcano,
    plot_fig4B_niche_marker_heatmap,
    plot_fig4C_pathway_bubble,
    compute_signature_score,
    plot_fig5A_signature_projection,
    plot_fig5B_validation_violin,
    plot_fig5C_sensitivity,
    _get_abundance,
    _proportions,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]


# ============================================================
# 参数解析
# ============================================================

def _parse_args() -> argparse.Namespace:
    results = _REPO_ROOT / "results"
    parser = argparse.ArgumentParser(
        description="Generate all paper figures for the spatial immunosuppressive niche study."
    )
    parser.add_argument("--hcc4r-niche-dir", type=Path,
                        default=results / "HCC4R" / "spatial_niche")
    parser.add_argument("--chc20-niche-dir", type=Path,
                        default=results / "CHC20" / "spatial_niche")
    parser.add_argument("--hcc4r-adata", type=Path,
                        default=results / "HCC4R" / "adata_vis_post.h5ad")
    parser.add_argument("--chc20-adata", type=Path,
                        default=results / "CHC20" / "adata_vis_post.h5ad")
    parser.add_argument("--scrna-adata", type=Path,
                        default=results / "HCC4R" / "adata_sc_post.h5ad")
    parser.add_argument("--hcc4r-visium-dir", type=Path,
                        default=_REPO_ROOT / "data" / "HCC4R",
                        help="HCC4R Visium Space Ranger 原始目录（用于读取 H&E 图）")
    parser.add_argument("--out-dir", type=Path,
                        default=results / "paper_figures")
    parser.add_argument("--dpi", type=int, default=PAPER_DPI)
    return parser.parse_args()


# ============================================================
# 日志配置
# ============================================================

def _setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
    )


# ============================================================
# 辅助：复制 Step 1 已生成的图
# ============================================================

def _copy_existing_figure(src: Path, dst: Path) -> None:
    """如果源文件存在则复制到目标路径，否则仅打印警告。"""
    if src.exists():
        shutil.copy2(src, dst)
        logging.info("Copied existing figure: %s → %s", src.name, dst.name)
    else:
        logging.warning("Expected figure not found (will be generated by Step 1): %s", src)


# ============================================================
# 数据加载
# ============================================================

def _load_data(args: argparse.Namespace):
    """加载所有上游结果文件，返回各数据对象（不存在时为 None）。"""

    # ── HCC4R niche scores CSV ──
    hcc4r_niche_csv = args.hcc4r_niche_dir / "spatial_niche_scores.csv"
    hcc4r_niche_df: Optional[pd.DataFrame] = None
    if hcc4r_niche_csv.exists():
        hcc4r_niche_df = pd.read_csv(hcc4r_niche_csv)
        logging.info("Loaded HCC4R niche scores: %d spots", len(hcc4r_niche_df))
    else:
        logging.warning(
            "HCC4R niche scores not found: %s\n"
            "  → Please run Step 2 first:\n"
            "    python code/pipeline/run_spatial_niche_analysis.py "
            "--adata results/HCC4R/adata_vis_post.h5ad "
            "--out-dir results/HCC4R/spatial_niche",
            hcc4r_niche_csv,
        )

    # ── HCC4R AnnData（空间转录组）──
    hcc4r_adata: Optional[ad.AnnData] = None
    if args.hcc4r_adata.exists():
        logging.info("Loading HCC4R AnnData: %s", args.hcc4r_adata)
        hcc4r_adata = ad.read_h5ad(args.hcc4r_adata)
        logging.info("HCC4R AnnData: %d spots × %d genes",
                     hcc4r_adata.n_obs, hcc4r_adata.n_vars)
    else:
        logging.warning("HCC4R AnnData not found: %s", args.hcc4r_adata)

    # ── HCC4R 细胞类型比例矩阵 ──
    hcc4r_prop_df: Optional[pd.DataFrame] = None
    if hcc4r_adata is not None:
        try:
            hcc4r_prop_df = _proportions(_get_abundance(hcc4r_adata))
        except Exception as e:
            logging.warning("Could not get HCC4R cell abundance: %s", e)

    # ── CHC20 AnnData（可选，用于 Figure 5）──
    chc20_adata: Optional[ad.AnnData] = None
    if args.chc20_adata.exists():
        logging.info("Loading CHC20 AnnData: %s", args.chc20_adata)
        chc20_adata = ad.read_h5ad(args.chc20_adata)

    # ── CHC20 niche scores CSV（可选）──
    chc20_niche_df: Optional[pd.DataFrame] = None
    chc20_niche_csv = args.chc20_niche_dir / "spatial_niche_scores.csv"
    if chc20_niche_csv.exists():
        chc20_niche_df = pd.read_csv(chc20_niche_csv)
        logging.info("Loaded CHC20 niche scores: %d spots", len(chc20_niche_df))

    return hcc4r_niche_df, hcc4r_adata, hcc4r_prop_df, chc20_adata, chc20_niche_df


def _load_signature_genes(args: argparse.Namespace, ranked_genes_csv: Path) -> list[str]:
    """Load HCC4R-derived immunosuppressive niche signature genes."""
    text_candidates = [
        args.hcc4r_niche_dir / "immunosuppressive_niche_signature_genes.txt",
        args.hcc4r_niche_dir.parent / "spatial_signature_genes.txt",
    ]
    for path in text_candidates:
        if path.exists():
            genes = [g.strip() for g in path.read_text(encoding="utf-8").splitlines()]
            genes = [g for g in genes if g]
            if genes:
                logging.info("Loaded HCC4R signature genes: %d from %s", len(genes), path)
                return genes

    if ranked_genes_csv.exists():
        ranked = pd.read_csv(ranked_genes_csv)
        for col in ["gene", "gene_symbol", "names", "index"]:
            if col in ranked.columns:
                genes = ranked[col].dropna().astype(str).str.strip().tolist()
                genes = [g for g in genes if g]
                if genes:
                    logging.info(
                        "Loaded HCC4R signature genes: %d from ranked CSV column '%s'",
                        len(genes), col,
                    )
                    return genes

    logging.warning(
        "No HCC4R signature gene list found. Checked: %s",
        ", ".join(str(p) for p in text_candidates + [ranked_genes_csv]),
    )
    return []


def _resolve_cell_types(
    hcc4r_prop_df: Optional[pd.DataFrame],
    hcc4r_niche_df: Optional[pd.DataFrame],
) -> tuple[list[str], list[str]]:
    """
    确定细胞类型列表。
    返回 (all_cell_types, key_cell_types_2B)
      - all_cell_types   : 用于 2C / 3B 等所有细胞类型
      - key_cell_types_2B: 用于 2B 空间丰度图的重点细胞类型
    """
    if hcc4r_prop_df is not None:
        all_cell_types = hcc4r_prop_df.columns.tolist()
    elif hcc4r_niche_df is not None:
        skip_cols = {
            "spot_id", "sample", "spatial_x", "spatial_y", "neighbor_radius",
            "immunosuppressive_gene_score", "neighborhood_cluster",
            "niche_semantic_label", "hep_high", "distance_to_hep_high",
            "has_hep_high_neighbor", "Treg_like_score", "immune_stroma_score",
            "immunosuppressive_niche_score", "niche_high", "spatial_region",
        }
        all_cell_types = [
            c for c in hcc4r_niche_df.columns
            if c not in skip_cols
            and not c.startswith("neighbor_")
            and not c.startswith("rank_")
        ]
    else:
        all_cell_types = [
            "Hepatocyte", "Malignant", "Treg", "T/NK",
            "Myeloid", "Fibroblast", "HSC", "B cell",
        ]

    # 2B 只展示最核心的 4 种
    key_cell_types_2B = ["Malignant", "HSC", "Treg", "Myeloid"]

    return all_cell_types, key_cell_types_2B


# ============================================================
# 主流程
# ============================================================

def main() -> int:
    _setup_logging()
    args = _parse_args()

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    logging.info("Paper figures output directory: %s", out_dir)

    dpi = args.dpi

    # ── 数据加载 ──────────────────────────────────────────────
    (hcc4r_niche_df,
     hcc4r_adata,
     hcc4r_prop_df,
     chc20_adata,
     chc20_niche_df) = _load_data(args)

    ranked_genes_csv = args.hcc4r_niche_dir / "immunosuppressive_niche_signature_genes_ranked.csv"
    all_cell_types, key_cell_types_2B = _resolve_cell_types(hcc4r_prop_df, hcc4r_niche_df)

    # ============================================================
    # ── Figure 1 ──────────────────────────────────────────────
    # ============================================================
    logging.info("=== Figure 1 ===")

    # 1A: 技术路线图（纯 matplotlib，无需数据文件）
    logging.info("Figure 1A: Workflow diagram...")
    plot_fig1A_workflow(out_dir, dpi=dpi)

    # 1C / 1D: 复制 Step 1 已生成的图
    if hcc4r_niche_df is not None:
        hcc4r_results_dir = args.hcc4r_niche_dir.parent
        for src_name, dst_name in [
            ("scrna_celltype_marker_heatmap.png", "fig1C_scrna_marker_heatmap.png"),
            ("t_cell_dotplot_horizontal.png",     "fig1D_treg_dotplot.png"),
        ]:
            _copy_existing_figure(hcc4r_results_dir / src_name, out_dir / dst_name)

    # ============================================================
    # ── Figure 2 ──────────────────────────────────────────────
    # ============================================================
    logging.info("=== Figure 2 ===")

    # 2A: H&E 图（需要 Visium 原始目录；无则用 placeholder）
    logging.info("Figure 2A: H&E image...")
    if hcc4r_niche_df is not None:
        plot_fig2A_HE(args.hcc4r_visium_dir, hcc4r_niche_df, out_dir, dpi=dpi)
    else:
        logging.warning("HCC4R niche df not available; skipping Figure 2A.")

    # 2B: 各细胞类型空间丰度散点图（每种独立文件）
    if hcc4r_niche_df is not None:
        logging.info("Figure 2B: Spatial abundance maps for %s...", key_cell_types_2B)
        plot_fig2B_spatial_abundance(
            hcc4r_niche_df,
            cell_types=key_cell_types_2B,
            out_dir=out_dir,
            sample_name="HCC4R",
            dpi=dpi,
        )
    else:
        logging.warning("HCC4R niche df not available; skipping Figure 2B.")

    # 2C: 细胞类型共定位相关性热图
    if hcc4r_prop_df is not None:
        logging.info("Figure 2C: Co-localization heatmap (from abundance)...")
        plot_fig2C_coloc_heatmap(
            hcc4r_prop_df,
            cell_types=all_cell_types,
            out_dir=out_dir,
            sample_name="HCC4R",
            dpi=dpi,
        )
    elif hcc4r_niche_df is not None:
        logging.info("Figure 2C: Co-localization heatmap (from niche df)...")
        prop_cols = [c for c in all_cell_types if c in hcc4r_niche_df.columns]
        if prop_cols:
            plot_fig2C_coloc_heatmap(
                hcc4r_niche_df[prop_cols],
                cell_types=prop_cols,
                out_dir=out_dir,
                sample_name="HCC4R",
                dpi=dpi,
            )
    else:
        logging.warning("No abundance data; skipping Figure 2C.")

    # ============================================================
    # ── Figure 3 ──────────────────────────────────────────────
    # ============================================================
    logging.info("=== Figure 3 ===")

    if hcc4r_niche_df is not None:
        logging.info("Figure 3A: Spatial domain map...")
        plot_fig3A_spatial_domain(hcc4r_niche_df, out_dir, dpi=dpi)

        logging.info("Figure 3B: Domain composition barplot...")
        plot_fig3B_domain_composition(
            hcc4r_niche_df,
            cell_types=all_cell_types,
            out_dir=out_dir,
            dpi=dpi,
        )

        logging.info("Figure 3C: Score violin plots...")
        plot_fig3C_score_violins(hcc4r_niche_df, out_dir, dpi=dpi)
    else:
        logging.warning("HCC4R niche df not available; skipping Figure 3.")

    # ============================================================
    # ── Figure 4 ──────────────────────────────────────────────
    # ============================================================
    logging.info("=== Figure 4 ===")

    if hcc4r_niche_df is not None and hcc4r_adata is not None:
        logging.info("Figure 4A: Volcano plot...")
        plot_fig4A_volcano(hcc4r_niche_df, hcc4r_adata, out_dir, dpi=dpi)

        logging.info("Figure 4B: Niche marker heatmap (top 30)...")
        plot_fig4B_niche_marker_heatmap(
            hcc4r_adata,
            hcc4r_niche_df,
            ranked_genes_csv,
            out_dir=out_dir,
            top_n=30,
            dpi=dpi,
        )

        logging.info("Figure 4C: Pathway bubble plot...")
        plot_fig4C_pathway_bubble(hcc4r_adata, hcc4r_niche_df, out_dir, dpi=dpi)
    else:
        logging.warning("HCC4R data not available; skipping Figure 4.")

    # ============================================================
    # ── Figure 5 ──────────────────────────────────────────────
    # ============================================================
    logging.info("=== Figure 5 ===")

    signature_genes = _load_signature_genes(args, ranked_genes_csv)
    hcc4r_signature_df: Optional[pd.DataFrame] = None
    chc20_signature_df: Optional[pd.DataFrame] = None
    hcc4r_matched_genes: list[str] = []
    chc20_matched_genes: list[str] = []

    if signature_genes and hcc4r_adata is not None:
        hcc4r_score, hcc4r_matched_genes = compute_signature_score(
            hcc4r_adata, signature_genes, score_name="hcc4r_signature_score"
        )
        if not hcc4r_score.empty:
            hcc4r_signature_df = pd.DataFrame({
                "spot_id": hcc4r_score.index,
                "sample": "HCC4R",
                "hcc4r_signature_score": hcc4r_score.to_numpy(dtype=float),
            })

    if signature_genes and chc20_adata is not None:
        chc20_score, chc20_matched_genes = compute_signature_score(
            chc20_adata, signature_genes, score_name="hcc4r_signature_score"
        )
        if not chc20_score.empty:
            chc20_signature_df = pd.DataFrame({
                "spot_id": chc20_score.index,
                "sample": "CHC20",
                "hcc4r_signature_score": chc20_score.to_numpy(dtype=float),
            })

            logging.info("Figure 5A: HCC4R-derived niche signature projected onto CHC20...")
            plot_fig5A_signature_projection(
                chc20_adata, chc20_score, out_dir=out_dir,
                signature_name="HCC4R-derived niche signature",
                matched_genes=chc20_matched_genes, dpi=dpi,
            )
        else:
            logging.warning("CHC20 has too few HCC4R signature genes; skipping Figure 5A.")
    else:
        logging.warning(
            "Missing data for Figure 5A. Need HCC4R signature genes and CHC20 adata_vis_post.h5ad."
        )

    if hcc4r_signature_df is not None and chc20_signature_df is not None:
        signature_score_csv = out_dir / "fig5_signature_scores_HCC4R_CHC20.csv"
        pd.concat([hcc4r_signature_df, chc20_signature_df], ignore_index=True).to_csv(
            signature_score_csv, index=False
        )
        logging.info("Saved Figure 5 signature scores: %s", signature_score_csv)

        used_genes = [g for g in signature_genes if g in set(chc20_matched_genes)]
        if not used_genes:
            used_genes = chc20_matched_genes
        (out_dir / "fig5_signature_genes_used_CHC20.txt").write_text(
            "\n".join(used_genes), encoding="utf-8"
        )

        logging.info("Figure 5B: HCC4R vs CHC20 signature score distribution...")
        plot_fig5B_validation_violin(
            hcc4r_signature_df, chc20_signature_df,
            out_dir=out_dir, dpi=dpi,
        )
    else:
        logging.warning(
            "Missing HCC4R or CHC20 signature score; skipping Figure 5B."
        )

    # 5C: 敏感性分析 + 参数扫描（直接读取 Step 2 输出的 CSV）
    logging.info("Figure 5C: Sensitivity analysis...")
    plot_fig5C_sensitivity(args.hcc4r_niche_dir, out_dir, dpi=dpi)

    # ============================================================
    # 汇总
    # ============================================================
    generated = sorted(out_dir.glob("*.png"))
    logging.info(
        "\n=== Paper figures generation complete ===\n"
        "Output directory : %s\n"
        "Total figures    : %d\n"
        "File list:\n  %s",
        out_dir,
        len(generated),
        "\n  ".join(f.name for f in generated),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
